1116_TDD/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('blog/', views.post_list, name='post_list'),
    # path('blog/new/', views.post_new, name='post_new'),
    path('blog/<int:pk>/', views.post_detail, name='post_detail'),
]

1116_TDD/tdd/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

1116_TDD/blog/models.py
from django.db import models

class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)

1116_TDD/blog/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content'] 
        widgets ={
            'title': forms.TextInput(attrs={'class': 'form-control postform'}),
            'content': forms.Textarea(attrs={'class': 'form-control postform', 'rows': 8, 'placeholder' : "글을 작성해주세요"}),
        }

1116_TDD/blog/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from django.views.generic import TemplateView
from .forms import PostForm
from .models import Post

class IndexView(TemplateView):
    template_name = 'blog/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context['key'] = 'value'
        return context
    
index = IndexView.as_view()

class AboutView(TemplateView):
    template_name = 'blog/about.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context
    
about = AboutView.as_view()

class ContactView(TemplateView):
    template_name = 'blog/contact.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context
    
contact = ContactView.as_view()

class PostListView(ListView):
    model = Post
    template_name = 'blog/post_list.html'

    def get_queryset(self):
        qs = super().get_queryset()
        q = self.request.GET.get('q', '')
        if q:
            qs = qs.filter(title__icontains=q)
        return qs

post_list = PostListView.as_view()

class PostDetailView(DetailView):
    model = Post 
    
    def get_object(self, queryset=None):
        pk = self.kwargs.get('pk')
        post = Post.objects.get(pk=pk)
        post.save()
        return super().get_object(queryset)

post_detail = PostDetailView.as_view()

1116_TDD/templates/blog/about.html
<!DOCTYPE html>
<html lang="ko-KR">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>about</title>
</head>

<body>
    <header>about header</header>
    about page
    <footer>about footer</footer>
</body>
</html>

1116_TDD/templates/blog/contact.html
<!DOCTYPE html>
<html lang="ko-KR">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>contact</title>
</head>

<body>
    <header>contact header</header>
    contact
    <footer>contact footer</footer>
</body>
</html>

1116_TDD/templates/blog/index.html
<!DOCTYPE html>
<html lang="ko-KR">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>index</title>
</head>

<body>
    <header>index header</header>
    index
    <footer>index footer</footer>
</body>
</html>

1116_TDD/templates/blog/post_detail.html
<!DOCTYPE html>
<html lang="ko-KR">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>post_detail</title>
</head>

<body>
    <header>post_detail header</header>

    <section class='contents-section'>
        <h2 class='contents-heading'>{{ post.title }}</h2>
        <p class='contents-text'>{{ post.content }}</p>
        <p class='contents-updated'>최종 수정 날짜: {{ post.updated_at }}</p>
    </section>

    <footer>post_detail footer</footer>
</body>
</html>

1116_TDD/templates/blog/post_list.html
<!DOCTYPE html>
<html lang="ko-KR">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BLOG main</title>
</head>

<body>
    <header>post_list header</header>

    {% if post_list.exists %}
    {% for post in object_list %}
            <section class="body">
                <h2 class='contents-heading'>{{ post.title }}</h2>
                <p class='contents-text'>{{ post.content }}</p>
                <p class='contents-updated' style="font-size: small;">최종 수정 날짜: {{ post.updated_at }}</p>
                <a class="btn" href="{% url 'blog:post_detail' post.pk %}">자세히</a>
                <br><br><br><br>
            </section>
    {% endfor %}
    {% else %}
    <p>게시물이 없습니다. 첫번째 게시물에 주인공이 되세요!</p>
    {% endif %}

    <footer>post_list footer</footer>
</body>
</html>